WITH REC
AS (SELECT *--Часть 1:Создание и заполнение полей "шахматной доски"
    FROM DUAL
    MODEL
    DIMENSION BY (1 i, 1 j)
    MEASURES (0 NUM)
    RULES (NUM[FOR i FROM 1 TO 8 INCREMENT 1,FOR j FROM 1 TO 8 INCREMENT 1]=SUM(NUM)[ANY,ANY]+1))
SELECT A.NUM A,B.NUM B,C.NUM C, D.NUM D, E.NUM E, F.NUM F, G.NUM G, H.NUM H, J " "--Часть 2: Формирование доски 
FROM (SELECT NUM,j FROM REC WHERE i=1)A JOIN(SELECT NUM,j FROM REC WHERE i=2)B USING(j) JOIN (SELECT NUM,j FROM REC WHERE i=3)C USING(j)
JOIN (SELECT NUM,j FROM REC WHERE i=4)D USING(j) JOIN (SELECT NUM,j FROM REC WHERE i=5)E USING(j)
JOIN (SELECT NUM,j FROM REC WHERE i=6)F USING(j) JOIN (SELECT NUM,j FROM REC WHERE i=7)G USING(j)
JOIN (SELECT NUM,j FROM REC WHERE i=8)H USING(j);

--Альтернативное решение
WITH REC(NUM,SUM,I)--формируем столбец со значениями клеток, i от 1 до 64
AS(SELECT 1,0,1
   FROM DUAL
   UNION ALL
   SELECT NUM+SUM+1,SUM+NUM,I+1
   FROM REC
   WHERE I<64)
SELECT A.NUM A,B.NUM B,C.NUM C,D.NUM D,E.NUM E,F.NUM F,G.NUM G,H.NUM H,ROWNUM " "--формирование доски соединением столбца по условию
FROM REC A JOIN REC B ON A.I=B.I-8 AND A.I<9
JOIN REC C ON B.I=C.I-8 AND B.I<17
JOIN REC D ON C.I=D.I-8 AND C.I<25 
JOIN REC E ON D.I=E.I-8 AND D.I<33
JOIN REC F ON E.I=F.I-8 AND E.I<41
JOIN REC G ON F.I=G.I-8 AND F.I<49
JOIN REC H ON G.I=H.I-8 AND G.I<57;
