SELECT MEMBER_CHILD ROOT_MEMBER,
(SELECT SUM(FEE)--подсчет бонусов нижестоящих партнеров
 FROM MLM_NET MN2 JOIN MLM_FEE MF ON MN2.MEMBER_CHILD=MF.MEMBER
 START WITH MN2.MEMBER_CHILD=MN1.MEMBER_CHILD
 CONNECT BY PRIOR MN2.MEMBER_CHILD= MN2.MEMBER_PARENT
)TOTAL_FEE
FROM MLM_NET MN1 JOIN MLM_FEE MF ON MN1.MEMBER_CHILD=MF.MEMBER
WHERE MEMBER_PARENT IS NULL--только для "корней"
START WITH MEMBER_PARENT IS NULL
CONNECT BY PRIOR MEMBER_CHILD=MEMBER_PARENT
ORDER BY TOTAL_FEE-MF.FEE DESC;
